### ISSUE TITLE
flymd.html got deleted in the elpa folder 

### ISSUE THREAD

**Issue by shelper** [mola-T/flymd#2]
So i turned on the auto deletion of html file after closing the md file buffer, 
then i use emacs open the flymd.html file in the elpa folder, and when i close the buffer for this flymd.html file. the file got deleted....
after reading the source code little bit i think it is because the program tries to delete any flymd.html after closing any buffer...

i would suggest to first check if the closed buffer is for the md file rendered by flymd before deleting the flymd.html.

**Comment by mola-T** [comment]
It only happens when you are opening and using `flymd-flyit` in `flymd` library location.

**Comment by shelper** [comment]
i totally agree, i am not bothered by this, but i just feel it would be better in terms of software quality....

**Comment by mola-T** [comment]
If you work on markdown in folder `A`, `flymd.html` in folder `A` got created and deleted.

If you work on markdown in folder `B`, `flymd.html` in folder `B` got created and deleted.

So, if you work on markdown in folder `flymd`, `flymd.html` in folder `flymd` got created and deleted.

What is the problem?

**Comment by shelper** [comment]
the problem is 
if i have a file happens to have the same name of flymd.html and i open it using emacs, 
and when i close the buffer, this file get deleted

**Comment by mola-T** [comment]
No it won't, unless you flyit in the same folder
