### ISSUE TITLE
add realtime mathjax and code highlite

### ISSUE THREAD

**Issue by shelper** [mola-T/flymd#3]
Fymd has  MathJaxize and GFMize buttons  to enable the mathjax rendering of equations but it cannot be enabled for auto refresh, although it might be slow and problematic with these two functions and auto refresh enabled the same time, it would be nice to give user the option to enable the mathjax and syntax highlighting at their own risk of being slow.

**Comment by mola-T** [comment]
1. Code highlight
   There is no such a "code hightlight" function. It is one of the side effects of `GFMize`. What `GFMize` done is to send your markdown to github and github converts the markdown to html for you. After the conversion, github sends the html back. When the html matches the css which is github flavored, the code highlights correctly. Besides it is too slow for realtime, github does not allow more than 60 request per hour. So `GFMize` cannot be realtime.

2. Realtime MathJax
   MathJax API works directly on DOM and its conversion process is not atomic. If you pay attention to the screen when you click `MathJaxize`, the browser display first the one line equation and then apply correct layout to the equation. If this is realtime, you could only see the screen flickering.

**Comment by shelper** [comment]
thanks for the explanation, its very clear.

**Comment by shelper** [comment]
i know this will involve much code changes, but 
for 1: i believe there are packages can be used locally to convert the .md code block to syntax highlighted code blocks in html,  why not using that one? using GITHUB causes problems when you don't have network connection

for 2: only render when a pattern of $$...$$ was identified, so no new equation, no rendering using Mathjax, that might solve the issue, at least partially
